package records;

import java.util.Objects;

public record AnotherPersonRecord(String name, String address) {

    // static member
    public static String UNKNOWN = "Unknown";

    // while a public constructor is generated
    // we can still customize out constructor
    // It is intended to be used for validation
    // and should be kept as simple as possible
    // also called COMPACT constructor
    public AnotherPersonRecord {
        Objects.requireNonNull(address);
    }

    // we can also create other constructor with different arguments
    public AnotherPersonRecord(String name) {
        this(name, "unknown");
    }

    // we can also create public constructor
    // with same arguments as generated by the public constructor
    // then we need to initialize this field manually
    // however, it cannot be used along with COMPACT constructor - will give compilation error
//    public AnotherPersonRecord(String name, String address) {
//        this.name = name;
//        this.address = address;
//    }

    // static method
    public static AnotherPersonRecord unnamed(String address) {
        return new AnotherPersonRecord(UNKNOWN, address);
    }
}
